# Generated by Django 3.2.7 on 2021-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210918_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.TimeField(),
        ),
    ]
